from django.urls import path
from . import views

app_name = "director"
urlpatterns = [
    path("", views.overview, name="overview"),
    path("growth/", views.growth, name="growth"),
    path("readiness/", views.readiness, name="readiness"),
    path("objectives/", views.objectives, name="objectives"),
    path("objectives/new/", views.objective_edit, name="objective_create"),
    path("objectives/<int:pk>/edit/", views.objective_edit, name="objective_edit"),
    path("decisions/", views.decisions, name="decisions"),
    path("decisions/new/", views.decision_edit, name="decision_create"),
    path("decisions/<int:pk>/", views.decision_detail, name="decision_detail"),
    path("decisions/<int:pk>/edit/", views.decision_edit, name="decision_edit"),
    path("decisions/<int:pk>/actions/<str:action>/", views.decision_action, name="decision_action"),
    path("budgets/", views.budgets, name="budgets"),
    path("budgets/new/", views.budget_edit, name="budget_create"),
    path("budgets/<int:pk>/", views.budget_detail, name="budget_detail"),
    path("budgets/<int:pk>/edit/", views.budget_edit, name="budget_edit"),
    path("budgets/<int:pk>/actions/<str:action>/", views.budget_action, name="budget_action"),
    path("budgets/<int:pk>/entries/new/", views.budget_entry, name="budget_entry"),
    path("budgets/<int:pk>/entries/<int:entry_pk>/replace/", views.budget_entry, name="budget_entry_replace"),
    path("cash/", views.cash, name="cash"),
    path("cash/new/", views.cash_edit, name="cash_create"),
    path("cash/<int:pk>/", views.cash_detail, name="cash_detail"),
    path("cash/<int:pk>/edit/", views.cash_edit, name="cash_edit"),
    path("cash/<int:pk>/lines/new/", views.cash_line, name="cash_line"),
    path("cash/<int:pk>/lines/<int:line_pk>/replace/", views.cash_line, name="cash_line_replace"),
    path("marketing/", views.marketing, name="marketing"),
    path("marketing/new/", views.marketing_edit, name="marketing_create"),
    path("marketing/import/", views.marketing_import, name="marketing_import"),
    path("marketing/template/", views.marketing_template, name="marketing_template"),
    path("marketing/<int:pk>/replace/", views.marketing_edit, name="marketing_replace"),
    path("records/<str:kind>/<int:pk>/void/", views.void_record, name="void_record"),
    path("scenarios/", views.scenarios, name="scenarios"),
    path("scenarios/new/", views.scenario_create, name="scenario_create"),
    path("scenarios/<int:pk>/", views.scenario_detail, name="scenario_detail"),
    path("ai/", views.assistant, name="assistant"),
    path("ai/policy/", views.ai_policy, name="ai_policy"),
    path("reports/", views.reports, name="reports"),
    path("reports/export/", views.export, name="export"),
    path("reports/document/", views.report_pdf, name="report_pdf"),
    path("api/snapshot/", views.snapshot_api, name="snapshot_api"),
]
