# Generated by Django 5.2.17 on 2026-09-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('owner', 'Pemilik'), ('director', 'Direktur'), ('finance', 'Staf keuangan'), ('marketing', 'Tim marketing'), ('reviewer', 'Peninjau pajak'), ('auditor', 'Pembaca laporan')], default='finance', max_length=20),
        ),
    ]
