# Generated by Django 5.2.17 on 2026-09-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_membership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner/Direktur'), ('marketing', 'Marketing'), ('finance', 'Finance'), ('director', 'Direktur (akses lama)'), ('reviewer', 'Peninjau pajak (akses lama)'), ('auditor', 'Pembaca laporan (akses lama)')], default='finance', max_length=20),
        ),
    ]
