# Generated by Django 5.2.17 on 2026-09-09 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_membership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='AccountSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totp_secret', models.TextField(blank=True)),
                ('totp_enabled', models.BooleanField(default=False)),
                ('totp_last_counter', models.BigIntegerField(default=-1)),
                ('recovery_codes', models.JSONField(default=list)),
                ('require_password_change', models.BooleanField(default=False)),
                ('session_version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_security', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
