# Generated by Django 5.2.17 on 2026-09-07 05:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=120)),
                ('account_number', models.CharField(max_length=80)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('opening_date', models.DateField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(max_length=160)),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.bankaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
            options={
                'ordering': ['-date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('number', models.CharField(max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('supplier_vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('date', models.DateField()),
                ('service_date', models.DateField()),
                ('category', models.CharField(choices=[('expense', 'Beban'), ('prepayment', 'Biaya dibayar di muka'), ('provider', 'Biaya penyedia tes')], default='expense', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draf'), ('approved', 'Disahkan')], default='draft', max_length=20)),
                ('tax_status', models.CharField(choices=[('review', 'Perlu tinjauan'), ('pending', 'Menunggu bukti'), ('reviewed', 'Ditinjau')], default='review', max_length=20)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
            options={
                'ordering': ['-date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.bill')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_payments', to='finance.banktransaction')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('number', models.CharField(max_length=80)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date', models.DateField()),
                ('due_date', models.DateField()),
                ('service_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draf'), ('issued', 'Diterbitkan'), ('delivered', 'Layanan selesai'), ('cancelled', 'Dibatalkan')], default='draft', max_length=20)),
                ('cost_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('delivered_at', models.DateField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
            options={
                'ordering': ['-date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.banktransaction')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=250)),
                ('source_key', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('draft', 'Draf'), ('posted', 'Terposting')], default='draft', max_length=10)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
            options={
                'ordering': ['-date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.CharField(choices=[('BANK', 'Bank'), ('AR', 'Piutang usaha'), ('DEFERRED_REVENUE', 'Pendapatan diterima di muka'), ('REVENUE', 'Pendapatan'), ('EXPENSE', 'Beban'), ('PREPAID', 'Biaya dibayar di muka'), ('AP', 'Utang usaha')], max_length=30)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='finance.journal')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('customer', 'Pelanggan'), ('reseller', 'Mitra reseller'), ('supplier', 'Pemasok')], max_length=20)),
                ('tax_id', models.CharField(blank=True, max_length=32)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
            options={
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='finance.party'),
        ),
        migrations.AddField(
            model_name='bill',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='finance.party'),
        ),
        migrations.CreateModel(
            name='PriceVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('selling', 'Harga jual'), ('supplier', 'Harga pemasok')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.party')),
            ],
            options={
                'ordering': ['-effective_from', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='price_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.priceversion'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('itp', 'TOEFL ITP'), ('ibt', 'TOEFL iBT'), ('course', 'Kursus')], max_length=20)),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='priceversion',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.product'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.product'),
        ),
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2200)])),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'year', 'month'), name='finance_org_period')],
            },
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(fields=('organization', 'account_number'), name='finance_bank_account_number'),
        ),
        migrations.AddConstraint(
            model_name='banktransaction',
            constraint=models.UniqueConstraint(fields=('organization', 'account', 'reference'), name='finance_bank_reference'),
        ),
        migrations.AddConstraint(
            model_name='banktransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='finance_bank_amount_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='billpayment',
            constraint=models.UniqueConstraint(fields=('bill', 'transaction'), name='finance_bill_payment_pair'),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.UniqueConstraint(fields=('invoice', 'transaction'), name='finance_receipt_invoice_pair'),
        ),
        migrations.AddConstraint(
            model_name='journal',
            constraint=models.UniqueConstraint(fields=('organization', 'source_key'), name='finance_journal_source_key'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('debit__gt', 0), ('credit', 0)), models.Q(('credit__gt', 0), ('debit', 0)), _connector='OR'), name='finance_journal_single_side'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(fields=('organization', 'supplier', 'number'), name='finance_bill_supplier_number'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='finance_product_org_code'),
        ),
        migrations.AddConstraint(
            model_name='priceversion',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='finance_price_dates'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('organization', 'number'), name='finance_invoice_org_number'),
        ),
    ]
