# Generated by Django 5.2.17 on 2026-09-09 02:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_documented_tax_workflows'),
        ('finance', '0001_initial'),
        ('taxes', '0002_documented_tax_workflows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalline',
            name='account',
            field=models.CharField(choices=[('BANK', 'Bank'), ('AR', 'Piutang usaha'), ('DEFERRED_REVENUE', 'Pendapatan diterima di muka'), ('REVENUE', 'Pendapatan'), ('EXPENSE', 'Beban'), ('PREPAID', 'Biaya dibayar di muka'), ('AP', 'Utang usaha'), ('EQUITY', 'Modal / saldo awal yang ditinjau'), ('BANK_TRANSFER', 'Transfer antarbank dalam perjalanan'), ('CUSTOMER_ADVANCE', 'Uang muka pelanggan belum diterapkan'), ('CUSTOMER_REFUND', 'Utang pengembalian pelanggan'), ('TAX_PAYABLE', 'Utang pajak potongan')], max_length=30),
        ),
        migrations.CreateModel(
            name='BankOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('reference', models.CharField(max_length=120)),
                ('evidence', models.TextField(max_length=4000)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='opening_record', to='finance.bankaccount')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.journal')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('reference', models.CharField(max_length=120)),
                ('evidence', models.TextField(max_length=4000)),
                ('kind', models.CharField(choices=[('bank_fee', 'Biaya bank'), ('owner_funding', 'Setoran modal pemilik'), ('transfer_out', 'Transfer keluar'), ('transfer_in', 'Transfer masuk'), ('customer_advance', 'Uang muka pelanggan'), ('customer_refund', 'Pengembalian pelanggan'), ('withheld_supplier', 'Pembayaran bersih pemasok'), ('tax_remittance', 'Penyetoran potongan pajak')], max_length=30)),
                ('signed_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.journal')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postings', to='finance.banktransaction')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('reference', models.CharField(max_length=120)),
                ('evidence', models.TextField(max_length=4000)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('bank_posting', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='finance.bankposting')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.journal')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_advances', to='finance.party')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdvanceApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('reference', models.CharField(max_length=120)),
                ('evidence', models.TextField(max_length=4000)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advance_applications', to='finance.invoice')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.journal')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('advance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='finance.customeradvance')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('reference', models.CharField(max_length=120)),
                ('evidence', models.TextField(max_length=4000)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('unpaid_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cancellation', to='finance.invoice')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.journal')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('reference', models.CharField(max_length=120)),
                ('evidence', models.TextField(max_length=4000)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('advance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='finance.customeradvance')),
                ('bank_posting', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='finance.bankposting')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.journal')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('cancellation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='finance.invoicecancellation')),
            ],
        ),
        migrations.CreateModel(
            name='PrepaymentRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('reference', models.CharField(max_length=120)),
                ('evidence', models.TextField(max_length=4000)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepayment_releases', to='finance.bill')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.journal')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='TaxRemittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('reference', models.CharField(max_length=120)),
                ('evidence', models.TextField(max_length=4000)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('bank_posting', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='finance.bankposting')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.journal')),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remittances', to='taxes.taxobligation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WithholdingSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('reference', models.CharField(max_length=120)),
                ('evidence', models.TextField(max_length=4000)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('withholding_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('bank_posting', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='finance.bankposting')),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='withholding_settlement', to='finance.bill')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.journal')),
                ('obligation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='withholding_settlement', to='taxes.taxobligation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='bankposting',
            constraint=models.UniqueConstraint(fields=('organization', 'reference'), name='finance_bank_posting_reference'),
        ),
        migrations.AddConstraint(
            model_name='bankposting',
            constraint=models.CheckConstraint(condition=models.Q(('signed_amount', 0), _negated=True), name='finance_bank_posting_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='advanceapplication',
            constraint=models.UniqueConstraint(fields=('organization', 'reference'), name='finance_advance_application_reference'),
        ),
        migrations.AddConstraint(
            model_name='customerrefund',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('advance__isnull', False), ('cancellation__isnull', True)), models.Q(('advance__isnull', True), ('cancellation__isnull', False)), _connector='OR'), name='finance_refund_one_source'),
        ),
        migrations.AddConstraint(
            model_name='prepaymentrelease',
            constraint=models.UniqueConstraint(fields=('organization', 'reference'), name='finance_prepayment_reference'),
        ),
    ]
