# Generated by Django 5.2.17 on 2026-09-07 05:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=160, unique=True)),
                ('window_start', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TaxSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('url', models.URLField(max_length=600)),
                ('issuer', models.CharField(default='Direktorat Jenderal Pajak / JDIH', max_length=100)),
                ('article', models.CharField(blank=True, max_length=200)),
                ('summary', models.TextField(max_length=2500)),
                ('topics', models.JSONField(default=list)),
                ('reviewed_on', models.DateField()),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Tanya pajak', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Pengguna'), ('assistant', 'Asisten')], max_length=12)),
                ('content', models.TextField(max_length=6000)),
                ('mode', models.CharField(blank=True, max_length=40)),
                ('source_ids', models.JSONField(default=list)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='taxes.chatconversation')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TaxObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(help_text='Hari pertama masa pajak')),
                ('tax_type', models.CharField(choices=[('pph23', 'PPh 23'), ('final_turnover', 'PPh final omzet'), ('corporate_income', 'PPh badan'), ('pph21', 'PPh 21'), ('pph26', 'PPh 26'), ('vat', 'PPN — kasus yang perlu ditinjau')], max_length=24)),
                ('direction', models.CharField(choices=[('payable', 'Potongan kepada pemasok — kewajiban setor'), ('receivable', 'Potongan oleh pelanggan — calon kredit pajak'), ('own_tax', 'Pajak perusahaan sendiri')], max_length=12)),
                ('base', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=6, help_text='Pecahan desimal, misalnya 0.02; kosong jika belum diputuskan', max_digits=9, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('source_reference', models.CharField(blank=True, max_length=300)),
                ('rule_reference', models.CharField(blank=True, max_length=300)),
                ('note', models.TextField(blank=True, max_length=4000)),
                ('status', models.CharField(choices=[('draft', 'Draf'), ('review', 'Perlu pemeriksaan'), ('approved', 'Disetujui pemeriksa')], default='draft', max_length=12)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, help_text='BPN/NTPN atau bukti alokasi deposit yang diverifikasi', max_length=200)),
                ('payment_verified_at', models.DateTimeField(blank=True, null=True)),
                ('filing_reference', models.CharField(blank=True, help_text='BPE atau bukti penerimaan resmi', max_length=200)),
                ('filing_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_obligations', to='core.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_tax_obligations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['period', 'tax_type', 'direction', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='TaxProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('registration_evidence', models.CharField(blank=True, max_length=300)),
                ('vat_status_evidence', models.CharField(blank=True, max_length=300)),
                ('vat_status_effective_from', models.DateField(blank=True, null=True)),
                ('regime', models.CharField(choices=[('undecided', 'Menunggu pemeriksaan dokumen'), ('final', 'PPh final omzet — telah ditinjau'), ('normal', 'PPh badan umum — telah ditinjau')], default='undecided', max_length=12)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('final_regime_start_date', models.DateField(blank=True, null=True)),
                ('final_regime_end_date', models.DateField(blank=True, null=True)),
                ('transition_evidence', models.CharField(blank=True, max_length=300)),
                ('review_note', models.TextField(blank=True, max_length=4000)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_profile', to='core.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_tax_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['organization', 'created_by'], name='taxes_chatc_organiz_005035_idx'),
        ),
        migrations.AddIndex(
            model_name='taxobligation',
            index=models.Index(fields=['organization', 'period'], name='taxes_taxob_organiz_2659b8_idx'),
        ),
        migrations.AddConstraint(
            model_name='taxobligation',
            constraint=models.CheckConstraint(condition=models.Q(('base__gte', 0), ('base__isnull', True), _connector='OR'), name='tax_base_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='taxobligation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0), ('amount__isnull', True), _connector='OR'), name='tax_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='taxobligation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rate__gte', 0), ('rate__lte', 1)), ('rate__isnull', True), _connector='OR'), name='tax_rate_valid'),
        ),
    ]
