# Generated by Django 5.2.17 on 2026-09-09 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_documented_tax_workflows'),
        ('finance', '0001_initial'),
        ('taxes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taxobligation',
            name='calculation_version',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='taxobligation',
            name='object_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='taxobligation',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prepared_tax_obligations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxobligation',
            name='reporting_method',
            field=models.CharField(choices=[('return_receipt', 'Bukti penerimaan SPT'), ('validated_self_payment', 'Pelaporan melalui pembayaran final tervalidasi')], default='return_receipt', max_length=24),
        ),
        migrations.AddField(
            model_name='taxobligation',
            name='rule_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='taxobligation',
            name='source_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_obligations', to='finance.bill'),
        ),
        migrations.CreateModel(
            name='AnnualTaxWorkpaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('book_snapshot', models.JSONField()),
                ('inputs', models.JSONField()),
                ('result', models.JSONField()),
                ('calculation_version', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalTaxReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_name', models.CharField(max_length=200)),
                ('qualification_reference', models.CharField(max_length=300)),
                ('reviewed_on', models.DateField()),
                ('statement', models.TextField(max_length=4000)),
                ('subject_type', models.CharField(max_length=30)),
                ('subject_id', models.PositiveBigIntegerField()),
                ('subject_digest', models.CharField(max_length=64)),
                ('decision', models.JSONField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillTaxDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_code', models.CharField(max_length=50)),
                ('base', models.DecimalField(decimal_places=2, max_digits=18)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=9)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('period', models.DateField()),
                ('reason', models.TextField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tax_decision', to='finance.bill')),
                ('obligation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_decision', to='taxes.taxobligation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('external_review', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='taxes.externaltaxreview')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnnualTaxApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('workpaper', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='approval', to='taxes.annualtaxworkpaper')),
                ('external_review', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='taxes.externaltaxreview')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='taxobligation',
            name='external_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obligations', to='taxes.externaltaxreview'),
        ),
        migrations.AddField(
            model_name='taxprofile',
            name='external_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='taxes.externaltaxreview'),
        ),
        migrations.CreateModel(
            name='TaxEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=200)),
                ('sha256', models.CharField(max_length=64)),
                ('content', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='externaltaxreview',
            name='evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taxes.taxevidence'),
        ),
        migrations.CreateModel(
            name='AnnualTaxFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=200)),
                ('taxpayer_reference', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('workpaper', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='filing', to='taxes.annualtaxworkpaper')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taxes.taxevidence')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='taxobligation',
            name='source_evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obligations', to='taxes.taxevidence'),
        ),
        migrations.CreateModel(
            name='TaxProfileDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('external_review', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='taxes.externaltaxreview')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='taxes.taxprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaxVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('payment', 'Pembayaran'), ('filing', 'Pelaporan'), ('credit', 'Bukti potong pelanggan')], max_length=12)),
                ('reference', models.CharField(max_length=200)),
                ('taxpayer_reference', models.CharField(max_length=100)),
                ('period', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('obligation_digest', models.CharField(max_length=64)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(max_length=4000)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taxes.taxevidence')),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verifications', to='taxes.taxobligation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('verifier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('obligation', 'kind'), name='tax_one_verification_kind'), models.UniqueConstraint(fields=('organization', 'kind', 'reference'), name='tax_unique_verified_reference')],
            },
        ),
    ]
