# Generated by Django 5.2.17 on 2026-09-09 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0002_documented_tax_workflows'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxprofile',
            name='taxpayer_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='TaxSourceRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField()),
                ('content_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='taxes.taxsource')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'content_hash'), name='tax_source_unique_revision')],
            },
        ),
    ]
