# Generated by Django 5.2.17 on 2026-09-07 06:18

import django.core.validators
import django.db.models.deletion
import evidence.models
import imports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_hash', models.CharField(max_length=64)),
                ('bundle_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('imported', 'Diimpor sebagai arsip sumber')], default='imported', max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='core.organization')),
                ('supplier_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_imports', to='finance.bill')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ImportException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exception_id', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=40)),
                ('message', models.TextField()),
                ('month_source_id', models.CharField(blank=True, max_length=160)),
                ('source_locator', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('open', 'Perlu ditinjau')], default='open', max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exceptions', to='imports.importbatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='MonthlySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_id', models.CharField(max_length=160)),
                ('source_period', models.CharField(max_length=7)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2200)])),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('source_page', models.PositiveIntegerField()),
                ('printed_count', models.PositiveIntegerField(blank=True, null=True)),
                ('printed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('detail_count', models.PositiveIntegerField(blank=True, null=True)),
                ('coverage', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='months', to='imports.importbatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
            options={
                'ordering': ['year', 'month'],
            },
        ),
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_id', models.CharField(max_length=160)),
                ('kind', models.CharField(max_length=40)),
                ('original_name', models.CharField(max_length=240)),
                ('sha256', models.CharField(max_length=64)),
                ('size', models.PositiveIntegerField()),
                ('page_count', models.PositiveIntegerField()),
                ('file', models.FileField(max_length=180, storage=evidence.models.PrivateEvidenceStorage(directory_permissions_mode=448, file_permissions_mode=384), upload_to=imports.models.source_document_path)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_documents', to='imports.importbatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.UniqueConstraint(fields=('organization', 'source_hash'), name='imports_org_source_hash'),
        ),
        migrations.AddConstraint(
            model_name='importexception',
            constraint=models.UniqueConstraint(fields=('batch', 'exception_id'), name='imports_batch_exception'),
        ),
        migrations.AddConstraint(
            model_name='monthlysnapshot',
            constraint=models.UniqueConstraint(fields=('organization', 'year', 'month'), name='imports_org_period'),
        ),
        migrations.AddConstraint(
            model_name='sourcedocument',
            constraint=models.UniqueConstraint(fields=('batch', 'source_id'), name='imports_batch_source_id'),
        ),
    ]
