# Generated by Django 5.2.17 on 2026-09-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbatch',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='importexception',
            name='source_locator',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
