# Generated by Django 5.2.17 on 2026-09-08 13:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_membership_role'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=180)),
                ('channel', models.CharField(choices=[('mitra', 'Mitra'), ('meta_ads', 'Meta Ads'), ('google_ads', 'Google Ads'), ('whatsapp', 'WhatsApp'), ('seo', 'SEO'), ('sales', 'Sales')], max_length=20)),
                ('objective', models.CharField(blank=True, max_length=250)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('paused', 'Ditunda'), ('completed', 'Selesai')], default='active', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.product')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=150)),
                ('received_at', models.DateTimeField()),
                ('channel', models.CharField(choices=[('mitra', 'Mitra'), ('meta_ads', 'Meta Ads'), ('google_ads', 'Google Ads'), ('whatsapp', 'WhatsApp'), ('seo', 'SEO'), ('sales', 'Sales')], max_length=20)),
                ('segment', models.CharField(choices=[('direct', 'Pembeli langsung'), ('reseller', 'Mitra reseller'), ('institution', 'Institusi')], default='direct', max_length=20)),
                ('region', models.CharField(default='Semua wilayah', max_length=120)),
                ('stage', models.CharField(choices=[('new', 'Baru'), ('contacted', 'Dihubungi'), ('qualified', 'Sesuai kebutuhan'), ('proposal', 'Penawaran'), ('won', 'Sepakat membeli'), ('lost', 'Tidak lanjut')], default='new', max_length=20)),
                ('first_response_at', models.DateTimeField(blank=True, null=True)),
                ('next_follow_up', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=4000)),
                ('version', models.PositiveIntegerField(default=1)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='marketing.campaign')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marketing_leads', to='finance.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.party')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.product')),
            ],
            options={
                'ordering': ['-received_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='LeadStageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_stage', models.CharField(blank=True, choices=[('new', 'Baru'), ('contacted', 'Dihubungi'), ('qualified', 'Sesuai kebutuhan'), ('proposal', 'Penawaran'), ('won', 'Sepakat membeli'), ('lost', 'Tidak lanjut')], max_length=20)),
                ('to_stage', models.CharField(choices=[('new', 'Baru'), ('contacted', 'Dihubungi'), ('qualified', 'Sesuai kebutuhan'), ('proposal', 'Penawaran'), ('won', 'Sepakat membeli'), ('lost', 'Tidak lanjut')], max_length=20)),
                ('occurred_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_events', to='marketing.lead')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
            options={
                'ordering': ['occurred_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='MarketingAIPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enabled', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('policy_version', models.PositiveIntegerField(default=1)),
                ('monthly_budget_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('request_cap_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('disclosure_version', models.CharField(default='marketing-aggregate-v1', max_length=80)),
                ('disclosure_text', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='marketing_ai_policy', to='core.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150)),
                ('discipline', models.CharField(choices=[('manager', 'Manajer'), ('media_buyer', 'Pengelola iklan'), ('content', 'Konten'), ('sales', 'Sales / follow-up'), ('partnership', 'Kemitraan')], max_length=20)),
                ('team', models.CharField(default='Marketing', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
            options={
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='MarketingAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('evidence', models.TextField(blank=True, max_length=4000)),
                ('description', models.TextField(max_length=4000)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Belum mulai'), ('in_progress', 'Dikerjakan'), ('done', 'Selesai'), ('dismissed', 'Tidak dilanjutkan')], default='open', max_length=20)),
                ('outcome', models.TextField(blank=True, max_length=4000)),
                ('metric_key', models.CharField(default='cash_in', max_length=60)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='marketing.teammember')),
            ],
            options={
                'ordering': ['due_date', '-created_at', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='marketing.teammember'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='marketing.teammember'),
        ),
        migrations.CreateModel(
            name='AdDailyObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('ad_name', models.CharField(default='Semua iklan', max_length=180)),
                ('audience', models.CharField(default='Semua audiens', max_length=160)),
                ('region', models.CharField(default='Semua wilayah', max_length=120)),
                ('spend', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('impressions', models.PositiveIntegerField(blank=True, null=True)),
                ('clicks', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.CharField(max_length=180)),
                ('reference', models.CharField(max_length=180)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='marketing.campaign')),
            ],
            options={
                'ordering': ['-date', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'reference'), name='marketing_ad_reference'), models.UniqueConstraint(fields=('organization', 'campaign', 'date', 'ad_name', 'audience', 'region'), name='marketing_ad_grain')],
            },
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(fields=('organization', 'reference'), name='marketing_lead_reference'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice__isnull', False)), fields=('invoice',), name='marketing_lead_invoice'),
        ),
    ]
