# Generated by Django 5.2.17 on 2026-09-08 13:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_membership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True)),
                ('reserved_usd', models.DecimalField(decimal_places=6, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2200)])),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('channel', models.CharField(choices=[('mitra', 'Mitra'), ('meta_ads', 'Meta Ads'), ('google_ads', 'Google Ads'), ('whatsapp', 'WhatsApp'), ('seo', 'SEO'), ('sales', 'Sales')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('draft', 'Draf'), ('submitted', 'Diajukan'), ('approved', 'Disetujui')], default='draft', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('approval_notes', models.TextField(blank=True, max_length=4000)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
            options={
                'ordering': ['-year', '-month', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='CashPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('as_of', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('reserve', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('unknown_obligations', models.TextField(blank=True, max_length=4000)),
                ('basis', models.CharField(choices=[('assumed', 'Simulasi dengan saldo asumsi')], default='assumed', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
            options={
                'ordering': ['-as_of', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='CashPlanLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('direction', models.CharField(choices=[('inflow', 'Penerimaan rencana'), ('outflow', 'Pengeluaran rencana')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=500)),
                ('source_reference', models.CharField(blank=True, max_length=200)),
                ('evidence', models.TextField(blank=True, max_length=4000)),
                ('status', models.CharField(choices=[('planned', 'Rencana'), ('void', 'Dibatalkan')], default='planned', max_length=10)),
                ('void_reason', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='director.cashplan')),
                ('replaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacements', to='director.cashplanline')),
            ],
            options={
                'ordering': ['date', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('problem', models.TextField(blank=True, max_length=4000)),
                ('evidence', models.TextField(blank=True, max_length=4000)),
                ('option', models.TextField(blank=True, max_length=4000)),
                ('risks', models.TextField(blank=True, max_length=4000)),
                ('owner_name', models.CharField(blank=True, max_length=150)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('draft', 'Draf'), ('submitted', 'Diajukan'), ('reviewed', 'Ditinjau Finance'), ('approved', 'Disetujui'), ('rejected', 'Ditolak'), ('active', 'Aktif'), ('completed', 'Selesai')], default='draft', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('review_notes', models.TextField(blank=True, max_length=4000)),
                ('approval_notes', models.TextField(blank=True, max_length=4000)),
                ('execution_notes', models.TextField(blank=True, max_length=4000)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='DirectorAIPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enabled', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('policy_version', models.CharField(default='1', max_length=20)),
                ('monthly_budget_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('request_cap_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('disclosure_version', models.CharField(default='director-aggregate-v1', max_length=80)),
                ('disclosure_text', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='director_ai_policy', to='core.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DirectorConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DirectorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('user', 'Pengguna'), ('assistant', 'AI')], max_length=12)),
                ('content', models.TextField()),
                ('response', models.JSONField(blank=True, default=dict)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='director.directorconversation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='MarketingObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('channel', models.CharField(choices=[('mitra', 'Mitra'), ('meta_ads', 'Meta Ads'), ('google_ads', 'Google Ads'), ('whatsapp', 'WhatsApp'), ('seo', 'SEO'), ('sales', 'Sales')], max_length=20)),
                ('spend', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('leads', models.PositiveIntegerField(blank=True, null=True)),
                ('paid_orders', models.PositiveIntegerField(blank=True, null=True)),
                ('reported_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('source', models.CharField(max_length=200)),
                ('reference', models.CharField(max_length=200)),
                ('basis', models.CharField(choices=[('reported', 'Dilaporkan sumber'), ('provisional', 'Sementara')], default='reported', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('void', 'Dibatalkan')], default='active', max_length=10)),
                ('void_reason', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('replaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacements', to='director.marketingobservation')),
            ],
            options={
                'ordering': ['-date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('metric_key', models.CharField(max_length=100)),
                ('target', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('owner_name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('draft', 'Draf'), ('active', 'Aktif'), ('paused', 'Ditunda'), ('completed', 'Selesai')], default='draft', max_length=20)),
                ('progress_notes', models.TextField(blank=True, max_length=4000)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
            options={
                'ordering': ['-period_start', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('price_cost', 'Harga, biaya, dan volume')], max_length=30)),
                ('inputs', models.JSONField(default=dict)),
                ('results', models.JSONField(default=dict)),
                ('formula_version', models.CharField(max_length=80)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='AIUsageReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_id', models.CharField(max_length=80)),
                ('amount_usd', models.DecimalField(decimal_places=6, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('reserved', 'Dipesan'), ('dispatching', 'Dikirim'), ('completed', 'Selesai'), ('outcome_unknown', 'Hasil belum diketahui'), ('released', 'Dilepas')], default='reserved', max_length=20)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'request_id'), name='director_ai_request_key')],
            },
        ),
        migrations.CreateModel(
            name='BudgetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('incurred', 'Biaya terjadi'), ('open_commitment', 'Komitmen tersisa'), ('reservation', 'Reservasi'), ('payment', 'Pembayaran tercatat')], max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('reference', models.CharField(blank=True, max_length=160)),
                ('idempotency_key', models.CharField(max_length=100)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=500)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='director.budget')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('replaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacements', to='director.budgetentry')),
            ],
            options={
                'ordering': ['-date', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='director_budget_entry_key')],
            },
        ),
    ]
