from django.contrib.auth.views import LogoutView
from django.urls import include, path
from webapp import views
from webapp import import_views
from taxes import views as tax_views
from config.health import readiness_response

urlpatterns = [
    path("", include("webapp.account_views")),
    path("", include("webapp.statement_views")),
    path("", include("webapp.operations_views")),
    path("marketing/", include("marketing.urls")),
    path("director/", include("director.urls")),
    path("", views.dashboard, name="dashboard"),
    path("login/", views.FinanceLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("demo/", views.demo_login, name="demo_login"),
    path("setup/", views.setup, name="setup"),
    path("sales/", views.sales, name="sales"),
    path("sales/new/", views.sale_create, name="sale_create"),
    path("sales/<int:pk>/", views.sale_detail, name="sale_detail"),
    path("sales/<int:pk>/document/", views.sale_pdf, name="sale_pdf"),
    path("sales/<int:pk>/attachments/", views.sale_attachment, name="sale_attachment"),
    path("sales/<int:pk>/issue/", views.sale_issue, name="sale_issue"),
    path("sales/<int:pk>/deliver/", views.sale_deliver, name="sale_deliver"),
    path("bills/", views.bills, name="bills"),
    path("bills/new/", views.bill_create, name="bill_create"),
    path("bills/<int:pk>/", views.bill_detail, name="bill_detail"),
    path("bills/<int:pk>/attachments/", views.bill_attachment, name="bill_attachment"),
    path("bills/<int:pk>/approve/", views.bill_approve, name="bill_approve"),
    path("bank/", views.bank, name="bank"),
    path("bank/template/", views.bank_template, name="bank_template"),
    path("bank/accounts/new/", views.bank_account_create, name="bank_account_create"),
    path("bank/<int:pk>/match/", views.bank_match, name="bank_match"),
    path("partners/", views.partners, name="partners"),
    path("partners/new/", views.partner_create, name="partner_create"),
    path("prices/", views.prices, name="prices"),
    path("prices/new/", views.price_create, name="price_create"),
    path("prices/<int:pk>/replace/", views.price_replace, name="price_replace"),
    path("products/new/", views.product_create, name="product_create"),
    path("reports/", views.reports, name="reports"),
    path("reports/export/", views.report_export, name="report_export"),
    path("reports/document/", views.report_pdf, name="report_pdf"),
    path("reports/close/", views.close_month, name="close_month"),
    path("settings/", views.settings_view, name="settings"),
    path("settings/tax/", views.tax_profile_setup, name="tax_profile_setup"),
    path("settings/team/new/", views.member_create, name="member_create"),
    path("settings/password/", views.password_change, name="password_change"),
    path("modules/", views.modules, name="modules"),
    path("tax/", tax_views.index, name="tax_workspace"),
    path("tax/annual/", tax_views.annual, name="annual_tax"),
    path("tax/chat/", tax_views.chat, name="chat"),
    path("tax/", include("taxes.urls")),
    path("evidence/", include("evidence.urls")),
    path("health/", views.health, name="health"),
    path("ready/", readiness_response, name="readiness"),
    path("imports/", import_views.overview, name="imports_overview"),
    path("imports/export/", import_views.export, name="imports_export"),
    path("imports/sources/<int:pk>/", import_views.source_download, name="import_source"),
    path("imports/<str:period>/", import_views.month, name="imports_month"),
]
