# Generated by Django 5.2.17 on 2026-09-09 02:24

import django.db.models.deletion
import evidence.models
import webapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_documented_tax_workflows'),
        ('finance', '0002_controlled_financial_movements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=evidence.models.PrivateEvidenceStorage(directory_permissions_mode=448, file_permissions_mode=384), upload_to=webapp.models.statement_path)),
                ('original_name', models.CharField(max_length=240)),
                ('sha256', models.CharField(max_length=64)),
                ('headers', models.JSONField(default=list)),
                ('rows', models.JSONField(default=list)),
                ('mapping', models.JSONField(default=dict)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.bankaccount')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_bank_imports', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'account', 'sha256'), name='unique_statement_file_account')],
            },
        ),
    ]
