# Generated by Django 5.2.17 on 2026-09-07 05:45

import django.core.validators
import django.db.models.deletion
import evidence.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(max_length=180, storage=evidence.models.PrivateEvidenceStorage(directory_permissions_mode=448, file_permissions_mode=384), upload_to=evidence.models.evidence_path)),
                ('original_name', models.CharField(max_length=240)),
                ('content_type', models.CharField(choices=[('application/pdf', 'PDF'), ('image/png', 'PNG'), ('image/jpeg', 'JPEG')], max_length=32)),
                ('size', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10485760)])),
                ('sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('\\A[a-f0-9]{64}\\Z', 'Hash SHA-256 tidak valid.')])),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='finance.bill')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='finance.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('bill__isnull', True), ('invoice__isnull', False)), models.Q(('bill__isnull', False), ('invoice__isnull', True)), _connector='OR'), name='evidence_exactly_one_source'), models.UniqueConstraint(fields=('organization', 'invoice', 'sha256'), name='evidence_invoice_hash'), models.UniqueConstraint(fields=('organization', 'bill', 'sha256'), name='evidence_bill_hash')],
            },
        ),
    ]
